/*
Copyright (c) 2024 Americus Maximus

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#pragma once

#define DIRECT3D_VERSION 0x800
#include <d3d8.h>

#define D3DLOCK_NONE 0
#define D3DUSAGE_NONE 0
#define D3DFVF_NONE 0

#define D3DFMT_UNKNOWN_1 (D3DFORMAT)1
#define D3DFMT_UNKNOWN_2 (D3DFORMAT)2
#define D3DFMT_UNKNOWN_3 (D3DFORMAT)3
#define D3DFMT_UNKNOWN_4 (D3DFORMAT)4
#define D3DFMT_UNKNOWN_5 (D3DFORMAT)5
#define D3DFMT_UNKNOWN_6 (D3DFORMAT)6
#define D3DFMT_UNKNOWN_7 (D3DFORMAT)7
#define D3DFMT_UNKNOWN_8 (D3DFORMAT)8
#define D3DFMT_UNKNOWN_9 (D3DFORMAT)9
#define D3DFMT_UNKNOWN_10 (D3DFORMAT)10
#define D3DFMT_UNKNOWN_11 (D3DFORMAT)11
#define D3DFMT_UNKNOWN_12 (D3DFORMAT)12
#define D3DFMT_UNKNOWN_13 (D3DFORMAT)13
#define D3DFMT_UNKNOWN_14 (D3DFORMAT)14
#define D3DFMT_UNKNOWN_15 (D3DFORMAT)15
#define D3DFMT_UNKNOWN_16 (D3DFORMAT)16
#define D3DFMT_UNKNOWN_17 (D3DFORMAT)17
#define D3DFMT_UNKNOWN_18 (D3DFORMAT)18
#define D3DFMT_UNKNOWN_19 (D3DFORMAT)19
#define D3DFMT_A2B10G10R10 (D3DFORMAT)31
#define D3DFMT_A8B8G8R8 (D3DFORMAT)32
#define D3DFMT_X8B8G8R8 (D3DFORMAT)33
#define D3DFMT_G16R16 (D3DFORMAT)34
#define D3DFMT_A2R10G10B10 (D3DFORMAT)35
#define D3DFMT_A16B16G16R16 (D3DFORMAT)36
#define D3DFMT_UNKNOWN_37 (D3DFORMAT)37
#define D3DFMT_UNKNOWN_38 (D3DFORMAT)38
#define D3DFMT_UNKNOWN_39 (D3DFORMAT)39
#define D3DFMT_UNKNOWN_42 (D3DFORMAT)42
#define D3DFMT_UNKNOWN_43 (D3DFORMAT)43
#define D3DFMT_UNKNOWN_44 (D3DFORMAT)44
#define D3DFMT_UNKNOWN_45 (D3DFORMAT)45
#define D3DFMT_UNKNOWN_46 (D3DFORMAT)46
#define D3DFMT_UNKNOWN_47 (D3DFORMAT)47
#define D3DFMT_UNKNOWN_48 (D3DFORMAT)48
#define D3DFMT_UNKNOWN_49 (D3DFORMAT)49
#define D3DFMT_UNKNOWN_53 (D3DFORMAT)53
#define D3DFMT_UNKNOWN_54 (D3DFORMAT)54
#define D3DFMT_UNKNOWN_55 (D3DFORMAT)55
#define D3DFMT_UNKNOWN_56 (D3DFORMAT)56
#define D3DFMT_UNKNOWN_57 (D3DFORMAT)57
#define D3DFMT_UNKNOWN_58 (D3DFORMAT)58
#define D3DFMT_UNKNOWN_59 (D3DFORMAT)59
#define D3DFMT_UNKNOWN_66 (D3DFORMAT)66
#define D3DFMT_UNKNOWN_67 (D3DFORMAT)67
#define D3DFMT_UNKNOWN_68 (D3DFORMAT)68
#define D3DFMT_UNKNOWN_69 (D3DFORMAT)69
#define D3DFMT_UNKNOWN_72 (D3DFORMAT)72
#define D3DFMT_UNKNOWN_74 (D3DFORMAT)74

#define RGBA_GETALPHA(rgb)      ((rgb) >> 24)
#define RGBA_GETRED(rgb)        (((rgb) >> 16) & 0xff)
#define RGBA_GETGREEN(rgb)      (((rgb) >> 8) & 0xff)
#define RGBA_GETBLUE(rgb)       ((rgb) & 0xff)
#define RGBA_MAKE(r, g, b, a)   ((D3DCOLOR) (((a) << 24) | ((r) << 16) | ((g) << 8) | (b)))